# Cloud Build configuration for deploying to Cloud Run
# 
# Prerequisites:
# 1. Enable Cloud Build, Cloud Run, and Cloud SQL APIs in your GCP project
# 2. Create a Cloud SQL PostgreSQL instance named 'the586-db'
# 3. Create a database named 'the586' in that instance
# 4. Set up Secret Manager secrets:
#    - DATABASE_URL: postgres://user:password@/the586?host=/cloudsql/PROJECT_ID:REGION:the586-db
#    - FIREBASE_SERVICE_ACCOUNT: Your Firebase admin SDK JSON (if using Firebase Auth)
#
# Deploy command:
# gcloud builds submit --config cloudbuild.yaml --substitutions=_REGION=us-central1

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: the586-api
  _INSTANCE_CONNECTION_NAME: ${PROJECT_ID}:${_REGION}:the586-db

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest'
      - '.'
    dir: 'backend'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=${_INSTANCE_CONNECTION_NAME}'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=60s'

images:
  - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}'
  - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest'

timeout: '1200s'
